-- Create tips table
CREATE TABLE IF NOT EXISTS public.tips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on tips
ALTER TABLE public.tips ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone
CREATE POLICY "Enable read access for all users" ON public.tips
    FOR SELECT USING (true);

-- Insert Tip of the Day content
INSERT INTO public.tips (title, content) VALUES
('A regra dos 50/30/20', 'Divida sua renda: 50% para necessidades, 30% para desejos e 20% para economias e investimentos. É um ótimo ponto de partida!'),
('Comece pequeno, mas comece', 'Mesmo R$ 50 por mês faz diferença. O importante é criar o hábito de investir regularmente.'),
('Reserva de emergência primeiro', 'Antes de investir em renda variável, tenha de 3 a 6 meses de gastos guardados em investimentos seguros e líquidos.'),
('Tempo é seu maior aliado', 'Graças aos juros compostos, quanto antes você começar, menos precisará investir para atingir seus objetivos.'),
('Diversifique seus investimentos', 'Não coloque todos os ovos na mesma cesta. Distribua entre diferentes tipos de investimento para reduzir riscos.');

-- Insert "Reserva de Emergência" term for Lesson 03
-- First, find the lesson ID for Lesson 03. Assuming title_short contains '03' or order_index is 3.
-- We use a DO block to find the ID and insert.
DO $$
DECLARE
    v_lesson_id BIGINT;
BEGIN
    SELECT id INTO v_lesson_id FROM public.lessons WHERE title_short LIKE '%03%' OR order_index = 3 LIMIT 1;

    IF v_lesson_id IS NOT NULL THEN
        INSERT INTO public.terms (lesson_id, acronym, name, explanation_full, explanation_simple, example, tip, category)
        VALUES (
            v_lesson_id,
            'RE',
            'Reserva de Emergência',
            'É o montante financeiro acumulado para cobrir despesas imprevistas e inadiáveis, garantindo sua estabilidade financeira em momentos de crise, como perda de emprego ou questões de saúde.',
            'Dinheiro guardado em aplicação segura para usar apenas em imprevistos graves.',
            'Se você gasta R$ 3.000 mensais, sua reserva deve ser entre R$ 9.000 (3 meses) e R$ 36.000 (12 meses).',
            'Jamais use esse dinheiro para compras ou viagens. Ele é seu seguro contra o azar!',
            'Fundamentos'
        );
    END IF;
END $$;
